import { config } from "dotenv"

config()

const MENSAJE_OK = process.env['MENSAJE_OK']

const USUARIO_NO_ENCONTRADO = process.env['USUARIO_NO_ENCONTRADO']
const USUARIO_SIN_PRIVILEGIOS = process.env['USUARIO_SIN_PRIVILEGIOS']
const USUARIO_CORREO_REQUERIDO = process.env['USUARIO_CORREO_REQUERIDO']
const USUARIO_PASSWORD_REQUERIDO = process.env['USUARIO_PASSWORD_REQUERIDO']
const USUARIO_ROL_REQUERIDO = process.env['USUARIO_ROL_REQUERIDO']
const USUARIO_NOMBRE_REQUERIDO = process.env['USUARIO_NOMBRE_REQUERIDO']
const USUARIO_APELLIDO_REQUERIDO = process.env['USUARIO_APELLIDO_REQUERIDO']
const USUARIO_ID_REQUERIDO = process.env['USUARIO_ID_REQUERIDO']

const ROL_NOMBRE_REQUERIDO = process.env['ROL_NOMBRE_REQUERIDO']
const ROL_ID_REQUERIDO = process.env['ROL_ID_REQUERIDO']

const CATEGORIA_NOMBRE_REQUERIDO = process.env['CATEGORIA_NOMBRE_REQUERIDO']

export { MENSAJE_OK, USUARIO_NO_ENCONTRADO, USUARIO_SIN_PRIVILEGIOS, USUARIO_CORREO_REQUERIDO,
     USUARIO_PASSWORD_REQUERIDO, USUARIO_ROL_REQUERIDO, USUARIO_NOMBRE_REQUERIDO, USUARIO_APELLIDO_REQUERIDO, 
     USUARIO_ID_REQUERIDO, ROL_NOMBRE_REQUERIDO, ROL_ID_REQUERIDO, CATEGORIA_NOMBRE_REQUERIDO }