import { config } from "dotenv"

config()

const MENSAJE_OK = process.env['MENSAJE_OK']

const USUARIO_NO_ENCONTRADO = process.env['USUARIO_NO_ENCONTRADO']
const USUARIO_SIN_PRIVILEGIOS = process.env['USUARIO_SIN_PRIVILEGIOS']
const USUARIO_CORREO_REQUERIDO = process.env['USUARIO_CORREO_REQUERIDO']
const USUARIO_PASSWORD_REQUERIDO = process.env['USUARIO_PASSWORD_REQUERIDO']

export { MENSAJE_OK, USUARIO_NO_ENCONTRADO, USUARIO_SIN_PRIVILEGIOS, USUARIO_CORREO_REQUERIDO, USUARIO_PASSWORD_REQUERIDO }